stages:
  - test

test_app:
  stage: test
  image: python:3.10-slim
  variables:
    PYTHONPATH: "$CI_PROJECT_DIR"
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest --maxfail=1 --disable-warnings -q
